name: AutoCorrect CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  autocorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@v4

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v2

      - name: Review Dog
        if: failure()
        uses: huacnlee/autocorrect-action@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true
