name: CI
on:
  push:

  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: check
        run: pnpm check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Verify formatting
        run: zig fmt .
